### ISSUE TITLE
Provider panic crash when specifying pairwise in auth block

### ISSUE THREAD

**Issue by JoshiiSinfield** [Juniper/terraform-provider-mist#15]
Given the following code:
```hcl
resource "mist_org_wlan" "test_open" {
  ssid         = "${local.resource_prefix}test"
  org_id       = local.mist_org_id
  template_id  = mist_org_wlantemplate.wlantemplate_one.id
  bands = ["5", "6"]
  vlan_enabled = true
  vlan_id      = 160
  auth = {
    type = "eap"
    anticlog_threshold = 16
    pairwise = ["wpa3"]
  }
  auth_servers = [
    {
      host            = "REDACTED"
      port            = 1812
      secret          = "REDACTED"
      keywrap_enabled = false
      keywrap_format  = ""
    }
  ]
  acct_interim_interval = 600
  acct_servers = [
    {
      host            = "REDACTED"
      port            = 1813
      secret          = "REDACTED"
      keywrap_enabled = false
      keywrap_format  = ""
    }
  ]

  apply_to = "site"
  interface = "all"

}
```

the provider crashes out with the following error:
```shell

Stack trace from the terraform-provider-mist_v0.1.25 plugin:

panic: interface conversion: interface {} is basetypes.StringValue, not models.WlanAuthPairwiseItemEnum

goroutine 113 [running]:
github.com/Juniper/terraform-provider-mist/internal/resource_org_wlan.authPairwiseTerraformToSdk(...)
        github.com/Juniper/terraform-provider-mist/internal/resource_org_wlan/terraform_to_sdk_auth.go:25
github.com/Juniper/terraform-provider-mist/internal/resource_org_wlan.authTerraformToSdk({0x1051c2ff0?, _}, _, {{0x2, 0x10}, {0x2, 0x0}, {0x2, 0x0}, {0x2, ...}, ...})
        github.com/Juniper/terraform-provider-mist/internal/resource_org_wlan/terraform_to_sdk_auth.go:58 +0x8cc
github.com/Juniper/terraform-provider-mist/internal/resource_org_wlan.TerraformToSdk({0x10518b568, 0x14000434210}, 0x14000287308)
        github.com/Juniper/terraform-provider-mist/internal/resource_org_wlan/terraform_to_sdk.go:106 +0xe68
github.com/Juniper/terraform-provider-mist/internal/provider.(*orgWlanResource).Create(0x14000710c30, {0x10518b568, 0x14000434210}, {{{{0x1051c03f8, 0x14000161290}, {0x104e92d80, 0x14000511860}}, {0x1051c4248, 0x140001164b0}}, {{{0x1051c03f8, ...}, ...}, ...}, ...}, ...)
        github.com/Juniper/terraform-provider-mist/internal/provider/org_wlan_resource.go:73 +0x150
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).CreateResource(0x140002b81e0, {0x10518b568, 0x14000434210}, 0x140004e75b8, 0x140004e7590)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_createresource.go:101 +0x400
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.(*Server).ApplyResourceChange(0x140002b81e0, {0x10518b568, 0x14000434210}, 0x1400067a4b0, 0x140004e76b0)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/server_applyresourcechange.go:57 +0x380
github.com/hashicorp/terraform-plugin-framework/internal/proto6server.(*Server).ApplyResourceChange(0x140002b81e0, {0x10518b568?, 0x140004340c0?}, 0x1400067a410)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/proto6server/server_applyresourcechange.go:55 +0x2e0
github.com/hashicorp/terraform-plugin-go/tfprotov6/tf6server.(*server).ApplyResourceChange(0x140002c0460, {0x10518b568?, 0x140000b5560?}, 0x140000e6850)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/tf6server/server.go:865 +0x2b4
github.com/hashicorp/terraform-plugin-go/tfprotov6/internal/tfplugin6._Provider_ApplyResourceChange_Handler({0x105101840, 0x140002c0460}, {0x10518b568, 0x140000b5560}, 0x1400044e000, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.23.0/tfprotov6/internal/tfplugin6/tfplugin6_grpc.pb.go:518 +0x1c0
google.golang.org/grpc.(*Server).processUnaryRPC(0x140002bc200, {0x10518b568, 0x140000b4ba0}, {0x1051c1f40, 0x14000474000}, 0x140000b2000, 0x140003a9710, 0x105fb6318, 0x0)
        google.golang.org/grpc@v1.65.0/server.go:1379 +0xb58
google.golang.org/grpc.(*Server).handleStream(0x140002bc200, {0x1051c1f40, 0x14000474000}, 0x140000b2000)
        google.golang.org/grpc@v1.65.0/server.go:1790 +0xb20
google.golang.org/grpc.(*Server).serveStreams.func2.1()
        google.golang.org/grpc@v1.65.0/server.go:1029 +0x8c
created by google.golang.org/grpc.(*Server).serveStreams.func2 in goroutine 51
        google.golang.org/grpc@v1.65.0/server.go:1040 +0x13c

Error: The terraform-provider-mist_v0.1.25 plugin crashed!
```

**Comment by tmunzer** [comment]
Hi @JoshiiSinfield , can you test with v0.1.26?

**Comment by JoshiiSinfield** [comment]
:ok_hand: spot on. tested with v0.1.27. 

Thanks again for fast turn-around!
