### ISSUE TITLE
Panic with mist_site_wxrule resource

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#24]
With the following HCL

```hcl
resource "mist_site_wxrule" "wxrule_one" {
  site_id     = "redacted"
  src_wxtags = [
    "IOT"
  ]
  enabled = true
  action  = "allow"
  dst_allow_wxtags = ["RFC-1918"]
  order = 2
}
```

I encounter a panic
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104839f70]

goroutine 12 [running]:
github.com/Juniper/terraform-provider-mist/internal/resource_site_wxrule.SdkToTerraform({_, _}, {0x140000e80b0, {0x0, 0x0, 0x0}, {0x0, 0x0, 0x0}, 0x1400000e6a0, ...})
        github.com/Juniper/terraform-provider-mist/internal/resource_site_wxrule/sdk_to_terraform.go:50 +0x4d0
github.com/Juniper/terraform-provider-mist/internal/provider.(*siteWxRuleResource).Create(0x1400035b870, {0x1057c3568, 0x14000351530}, {{{{0x1057f83f8, 0x140005aacf0}, {0x1054cad80, 0x140005aa720}}, {0x1057fc248, 0x1400039a550}}, {{{0x1057f83f8, ...}, ...}, ...}, ...}, ...)
        github.com/Juniper/terraform-provider-mist/internal/provider/site_wxrule_resource.go:99 +0x39c
```

It appears this seems to be related the templateId given the line it points to in the stack trace
https://github.com/Juniper/terraform-provider-mist/blob/1ed271bdd59248eeb33567143bd3ad306dc66590/internal/resource_site_wxrule/sdk_to_terraform.go#L50

**Comment by tmunzer** [comment]
Hi @zbuchheit , can you test with v0.1.29?

**Comment by zbuchheit** [comment]
I am now hitting an error 
```
mist_site_wxrule.wxrule_one: Creating...
╷
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to mist_site_wxrule.wxrule_one, provider
│ "provider[\"[registry.terraform.io/juniper/mist\](http://registry.terraform.io/juniper/mist%5C)"]" produced an unexpected new value:
│ .site_id: was cty.StringVal("redacted-redacted-redacted-redacted-redacted"), but now null.
│
│ This is a bug in the provider, which should be reported in the provider's own issue
│ tracker.
```

**Comment by tmunzer** [comment]
my bad, can you try with v0.1.30?

**Comment by zbuchheit** [comment]
that looks like it fixed it. Thanks!
