### ISSUE TITLE
Panic on mist_site_setting with latest release 0.1.37

### ISSUE THREAD

**Issue by zbuchheit** [Juniper/terraform-provider-mist#37]
The following hcl panics
```
terraform {
  required_providers {
    mist = {
      source  = "juniper/mist"
      version = "0.1.37"
    }
  }
}

resource "mist_site_setting" "site_one" {
  site_id = "redacted"
  ap_updown_threshold     = 5
  device_updown_threshold = 5
  gateway_mgmt = {
    app_probing = {
      custom_apps = [ {
          hostnames = [
            "example.com"
          ]
          protocol = "http"
          name = "value"
      } ]
    }
  }
}
```

```
goroutine 68 [running]:
github.com/Juniper/terraform-provider-mist/internal/planmodifiers.OnlyRefreshIfValueHasChangedModifier.PlanModifyString({{_, {_, _, _}}}, {_, _}, {{{0x14000403400, 0x5, 0x8}}, {0x1, ...}, ...}, ...)
        github.com/Juniper/terraform-provider-mist/internal/planmodifiers/only_refresh_if_value_changed.go:115 +0x190
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.AttributePlanModifyString({_, _}, {_, _}, {{{0x14000403400, 0x5, 0x8}}, {0x1, {0x14000403480, 0x5, ...}}, ...}, ...)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/attribute_plan_modification.go:2407 +0x7e0
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.AttributeModifyPlan({_, _}, {_, _}, {{{0x14000403400, 0x5, 0x8}}, {0x1, {0x14000403480, 0x5, ...}}, ...}, ...)
        github.com/hashicorp/terraform-plugin-framework@v1.11.0/internal/fwserver/attribute_plan_modification.go:114 +0x3964
github.com/hashicorp/terraform-plugin-framework/internal/fwserver.NestedAttributeObjectPlanModify({_, _}, {_, _}, {{{0x14000238d20, 0x4, 0x6}}, {0x1, {0x1400023cac0, 0x4, ...}}, ...}, ...)
```

it specifically calls out https://github.com/Juniper/terraform-provider-mist/blob/5263d2958a21c8bc61e354c03d07a6deb6ce2816/internal/planmodifiers/only_refresh_if_value_changed.go#L115

**Comment by zbuchheit** [comment]
fixed in latest release
